export const PORT = 'http://localhost:5000'; //local development
// export const PORT = "";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const HOSPITAL_LIST_LOADED = "HOSPITAL_LIST_LOADED";
export const HOSPITAL_LIST_LOADING = "HOSPITAL_LIST_LOADING";

export const SPECIALTY_LIST_LOADED = "SPECIALTY_LIST_LOADED";
export const SPECIALTY_LIST_LOADING = "SPECIALTY_LIST_LOADING";
export const SPECIALTY_DOCTOR_LIST_LOADED = "SPECIALTY_DOCTOR_LIST_LOADED";
export const SPECIALTY_DOCTOR_LIST_LOADING = "SPECIALTY_DOCTOR_LIST_LOADING";
export const DOCTOR_LIST_LOADED = "DOCTOR_LIST_LOADED";
export const DOCTOR_LIST_LOADING = "DOCTOR_LIST_LOADING";

export const BOOKING_DOCTOR = "BOOKING_DOCTOR";
export const BOOKING_LOADED = "BOOKING_LOADED";
export const BOOKING_LOADING = "BOOKING_LOADING";